class PasswordResetsController < ApplicationController
  skip_before_action :require_authentication

  # GET /password-reset
  # Form: enter your email to receive a reset link.
  def new; end

  # POST /password-reset
  # Always redirects with a neutral message — never reveals whether an email is registered.
  def create
    email  = params[:email].to_s.strip.downcase
    member = current_club.members.active.find_by(email: email)

    # member.password_reset_token is the Rails 8 signed JWT (auto-generated by
    # has_secure_password via generates_token_for :password_reset, expires_in: 2.hours).
    # No manual token generation needed — the mailer reads it directly.
    PasswordResetMailer.reset(member).deliver_later if member

    redirect_to new_session_path,
                notice: "If that email is registered, you'll receive a reset link shortly."
  end

  # GET /password-reset/:token
  # Form: enter a new password.
  def edit
    @member = find_member_by_token!
  end

  # PATCH /password-reset/:token
  def update
    @member = find_member_by_token!
    return if @member.nil?

    if @member.update(password_params)
      # Revoke all existing sessions so stolen tokens can't be replayed.
      # The new session created below is the only valid one going forward.
      @member.sessions.destroy_all
      start_new_session_for(@member, request)
      redirect_to root_path, notice: "Password updated — you're now signed in."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def find_member_by_token!
    # find_by_token_for returns nil when the token is expired, tampered, or unknown.
    # Scope to current_club for multi-tenancy: a token from Club A must not unlock Club B.
    member = Member.find_by_token_for(:password_reset, params[:token])
    if member.nil? || member.club_id != current_club.id
      redirect_to new_password_reset_path,
                  alert: "That reset link is invalid or has expired. Request a new one."
      return nil
    end
    member
  end

  def password_params
    params.require(:member).permit(:password, :password_confirmation)
  end
end
